# winvaz-gateway
server:
  port: 9500

spring:
  application:
    name: winvaz-gateway
  profiles:
    active: dev
  # Config
  cloud:
    config:
      uri: http://localhost:9600/

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/