# 服务端口号
server:
  port: 9200

# 服务名称
spring:
  application:
    name: winvaz-turbine
  # 配置文件
  profiles:
    active: dev

# Eureka配置
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# Turbine配置
turbine:
  app-config: winvaz-ribbon
#  cluster-name-expression: "default"
  combine-host-port: true