# 服务注册中心端口
server:
  port: 8763
# 服务名 ，很重要 ，后期 config 配置中心会以 服务名为标识找对应的 服务
spring:
  application:
    name: winvaz-eureka
  # 环境配置
#  profiles:
#    active: dev

# 服务注册中心实例的主机名
eureka:
  instance:
      hostname: peer-two
  client:
    # serviceUrl指向peer-one
    service-url:
      defaultZone: http://peer-one:8762/eureka